Feature/table component
pastelnetwork/pastel-electron-wallet pull request #130
Opened 2021-06-07 16:31 UTC by sanjanadhikari1

- [ ] complete table component and add it to the storybook
- [ ] complete checkbox component and add it to the storybook

2021-06-07 17:37 UTC, ihor-stack reviewed
There is conflict on this PR.

2021-06-07 18:40 UTC, ihor-stack approved these changes

2021-06-08 00:20 UTC, CrazyOptimist requested changes
![image](https://user-images.githubusercontent.com/55074937/121102314-48e22200-c7cb-11eb-9a51-7cee5ec77d56.png)
* I think the caret should be aligned at the middle vertically.
* For table story, could we use string data for one column instead of both numbers?

* Tooltip is not fully appearing in the storybook, could you put it a bit down? It's the same in the doc tab.

2021-06-08 00:20 UTC, CrazyOptimist commented on src/common/components/Table/Table.stories.tsx
> +  //   const [checked, setChecked] = useState(isChecked)
could you remove unused code.

2021-06-08 13:39 UTC, sanjanadhikari1 commented on src/common/components/Table/Table.stories.tsx
> +  //   const [checked, setChecked] = useState(isChecked)
fixed

2021-06-08 17:13 UTC, CrazyOptimist approved these changes

2021-06-09 01:03 UTC, merged