Screen portfolio buyer
pastelnetwork/pastel-electron-wallet pull request #135
Opened 2021-06-09 11:29 UTC by ngvtuan

##### Commits
- [x] Screen 5.5 - Portfolio Buyer

##### FreedCamp
- [x] [Screen 5.5 - Portfolio Buyer](https://freedcamp.com/view/2956183/tasks/40217557)

2021-06-09 18:03 UTC, ihor-stack reviewed
Need to solve conflict issue

2021-06-11 15:44 UTC, muhadovic requested changes

2021-06-11 15:44 UTC, muhadovic commented on src/common/components/NFTCard/NFTCard.tsx
>  export interface INFTCompactCardProps {
Please use the Type instead of the Interface.

2021-06-14 19:38 UTC, muhadovic requested changes

2021-06-14 23:00 UTC, CrazyOptimist approved these changes
Looks good to me.

2021-06-14 23:49 UTC, CrazyOptimist commented
Already merged by [PR#144](https://github.com/pastelnetwork/pastel-electron-wallet/pull/144)

2021-06-14 23:49 UTC, closed without merging