Feature/6.9 6.21 40112315
pastelnetwork/pastel-electron-wallet pull request #174
Opened 2021-06-29 20:42 UTC by muhadovic

https://freedcamp.com/dashboard/home/panel/task/40590174

Updated Screens [Screenshots]
- 6.9 Likes List
![image](https://user-images.githubusercontent.com/49214944/123862456-a714a780-d928-11eb-9f2a-c7e9998cc66d.png)

- 6.11 Change Status Modal
![image](https://user-images.githubusercontent.com/49214944/123862565-cb708400-d928-11eb-95ae-b10c52470835.png)
- 6.12 Change Status Auction
![image](https://user-images.githubusercontent.com/49214944/123862733-01156d00-d929-11eb-8978-67c99e2082ee.png)
- 6.14 deal Approved Modal
![image](https://user-images.githubusercontent.com/49214944/123863210-957fcf80-d929-11eb-86e0-02f0ff01d6f5.png)
- 6.18 Bit_live_auction
![image](https://user-images.githubusercontent.com/49214944/123861035-fce85000-d926-11eb-8e94-e885e7a7f831.png)
![image](https://user-images.githubusercontent.com/49214944/123862170-4d13e200-d928-11eb-8ad1-8e8e0f56ed4c.png)

- 6.19 Bid Buy
![image](https://user-images.githubusercontent.com/49214944/123864270-de845380-d92a-11eb-8a5a-fb4704235705.png)

2021-07-01 05:53 UTC, ngvtuan reviewed
![ui issue](https://user-images.githubusercontent.com/10944387/124072725-59548800-da6b-11eb-9832-aa2d59b8ed5e.jpg)

2021-07-01 05:53 UTC, ngvtuan commented on src/features/nft/nftModals/likeListData.ts
> +  { id: 0, date: '1 min ago', member: 'L TestName', sold: 1, followers: 4 },
For `date` field, I think we can use `datetime` and use `dayjs ` to show. Refer https://day.js.org/docs/en/display/from-now

2021-07-03 22:34 UTC, muhadovic commented on src/common/components/ProgressBar/ProgressBar.tsx
> +          style={{ width: percent + '%', backgroundColor: '#00B282' }}
This progress bar is the striped progress bar. So it needs to use the background and backgroundColor properties at the same time. If backgroundColor would be used with TailwindCSS class, it doesn't work. So I used the backgroundColor property. If you have a good solution, please let me know

2021-07-06 03:36 UTC, ngvtuan approved these changes

2021-07-08 03:22 UTC, goal-shevchenko requested changes
All looks good to me except for one changes.

2021-07-10 09:27 UTC, goal-shevchenko approved these changes

2021-07-12 19:08 UTC, merged