user can't find the imported spendable address
pastelnetwork/pastel-electron-wallet pull request #207
Opened 2021-08-09 08:53 UTC by ngvtuan

##### Fixed
- [x] user can't find the imported spendable address in the wallet(it's only appearing in the balance section), nor can't export/backup it
- [x] The "path" argument must be of type string.

##### FreedCamp
- [x] [user can't find the imported spendable address](https://freedcamp.com/view/2956183/tasks/41522618)

2021-08-09 15:53 UTC, CrazyOptimist requested changes
What are you fixing by this PR? I don't think you really understood the issue.
This issue has been found on the legacy version of wallet.

Reproducible steps:
- Install the latest release of wallet
- Import a existing private key from your former paper wallet.
- Try to export the private key you just imported. (bug 1)
- Send some amount of PSL to a new address, it will probably create a "change address"(try again and again until you see "change address")
- Try to export the private key of the new "change address" (bug 2)

Given the reproducible steps, I think it can be fixed it in the new wallet(or just branch off from the `release/1.0`, this can be treated as hotfix and we can merge it later to master, I mean if it's better for you to work on it).

2021-08-11 04:10 UTC, Dicklesworthstone approved these changes

2021-08-11 05:16 UTC, sanjanadhikari1 approved these changes

2021-08-11 05:21 UTC, ngvtuan commented
@CrazyOptimist  Yes. I thought it happens with the new wallet version. Let me check for the legacy version. And in this PR I have fixed the loading issue in the onboarding screen.

2021-08-11 05:23 UTC, CrazyOptimist commented
> @CrazyOptimist Yes. I thought it happens with the new wallet version. Let me check for the legacy version. And in this PR I have fixed the loading issue in the onboarding screen.

Got it, good to merge this. Sorry for confusion.

2021-08-11 05:24 UTC, CrazyOptimist approved these changes

2021-08-11 05:25 UTC, merged